//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentSteenAPI_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVCertification
    {
        public int CVCertificationId { get; set; }
        public int CVId { get; set; }
        public int YearOfPassing { get; set; }
        public string Certification { get; set; }
        public string Major { get; set; }
        public string University { get; set; }
        public int LocationId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual CV CV { get; set; }
    }
}
