//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentSteenAPI_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVExperience
    {
        public int CVExperienceId { get; set; }
        public int CVId { get; set; }
        public int YearOfJoining { get; set; }
        public string CompanyName { get; set; }
        public int IndustryTypeId { get; set; }
        public int CompanyLocationId { get; set; }
        public string Designation { get; set; }
        public int FunctionalAreaId { get; set; }
        public string ReportingToPerson { get; set; }
        public decimal Salary { get; set; }
        public string Resposibilities { get; set; }
        public string MoreDetails { get; set; }
    
        public virtual FunctionalArea FunctionalArea { get; set; }
        public virtual IndustryType IndustryType { get; set; }
        public virtual Location Location { get; set; }
        public virtual CV CV { get; set; }
    }
}
