//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentSteenAPI_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVSearchTag
    {
        public int CVSerachTagId { get; set; }
        public int CVId { get; set; }
        public int SearchTagMasterId { get; set; }
    
        public virtual SearchTagMaster SearchTagMaster { get; set; }
        public virtual CV CV { get; set; }
    }
}
