//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentSteenAPI_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployerUser
    {
        public int EmployerUserId { get; set; }
        public int EmployerId { get; set; }
        public int UserId { get; set; }
    
        public virtual Employer Employer { get; set; }
        public virtual Users Users { get; set; }
    }
}
