//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentSteenAPI_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employer()
        {
            this.EmployerUser = new HashSet<EmployerUser>();
            this.Jobs = new HashSet<Jobs>();
        }
    
        public int EmployerId { get; set; }
        public string EmployerName { get; set; }
        public string ContactPersonName { get; set; }
        public string CorporateEmailId { get; set; }
        public string ContactNumber { get; set; }
        public string Website { get; set; }
        public Nullable<int> EmployerMemberShipLevelId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> EmployerStatusId { get; set; }
        public Nullable<int> IndustryTypeId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual EmployerMembershipLevel EmployerMembershipLevel { get; set; }
        public virtual EmployerStatus EmployerStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployerUser> EmployerUser { get; set; }
        public virtual IndustryType IndustryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jobs> Jobs { get; set; }
    }
}
