//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentSteenAPI_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCertifications
    {
        public int JobCertificationId { get; set; }
        public int JobId { get; set; }
        public int CertificationId { get; set; }
    
        public virtual CertificationMaster CertificationMaster { get; set; }
        public virtual Jobs Jobs { get; set; }
    }
}
