//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentSteenAPI_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCV
    {
        public int JobCVId { get; set; }
        public int JobId { get; set; }
        public int CVId { get; set; }
        public int CVStatusId { get; set; }
        public System.DateTime SubmittedOn { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
    
        public virtual CV CV { get; set; }
        public virtual CVStatus CVStatus { get; set; }
        public virtual Jobs Jobs { get; set; }
        public virtual Users Users { get; set; }
    }
}
