//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentSteenAPI_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruiterJob
    {
        public int RecruiterJobId { get; set; }
        public int RecruiterId { get; set; }
        public int JobId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<bool> IsIntrested { get; set; }
    
        public virtual Recruiter Recruiter { get; set; }
        public virtual Users Users { get; set; }
        public virtual Jobs Jobs { get; set; }
    }
}
