//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentSteenAPI_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruiterFunctionalAreas
    {
        public int RecruiterFunctionalAreaId { get; set; }
        public int RecruiterId { get; set; }
        public int FunctionalAreaId { get; set; }
    
        public virtual FunctionalArea FunctionalArea { get; set; }
        public virtual Recruiter Recruiter { get; set; }
    }
}
