//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentSteenAPI_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruiter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recruiter()
        {
            this.RecruiterFunctionalAreas = new HashSet<RecruiterFunctionalAreas>();
            this.RecruiterIndustries = new HashSet<RecruiterIndustries>();
            this.RecruiterPreferredLocations = new HashSet<RecruiterPreferredLocations>();
            this.RecruiterUser = new HashSet<RecruiterUser>();
            this.RecruiterBankDetails = new HashSet<RecruiterBankDetails>();
            this.CV = new HashSet<CV>();
            this.RecruiterJob = new HashSet<RecruiterJob>();
        }
    
        public int RecruiterId { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string BrandName { get; set; }
        public string PrimaryContactNumber { get; set; }
        public string SecondaryContactNumber { get; set; }
        public string PrimaryEmailId { get; set; }
        public string SecondaryEmailId { get; set; }
        public string OnlineProfile { get; set; }
        public string RecruitmentHistory { get; set; }
        public int RecruiterMembershipLevelId { get; set; }
        public int CountryId { get; set; }
        public Nullable<int> RecruiterStatusId { get; set; }
        public Nullable<int> AlertsAndNotification { get; set; }
        public Nullable<int> YearsOfExperience { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Location Location { get; set; }
        public virtual RecruiterMembershipLevel RecruiterMembershipLevel { get; set; }
        public virtual RecruiterStatus RecruiterStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecruiterFunctionalAreas> RecruiterFunctionalAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecruiterIndustries> RecruiterIndustries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecruiterPreferredLocations> RecruiterPreferredLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecruiterUser> RecruiterUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecruiterBankDetails> RecruiterBankDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CV> CV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecruiterJob> RecruiterJob { get; set; }
    }
}
